### ISSUE TITLE
HTTP Not Found error when running on PR

### ISSUE THREAD

**Issue by pekala** [netlify/delta-action#31]
When running the action on a branch with a PR, I'm getting a `HttpError: Not Found` error in GitHub Actions logs:

```
(node:2502) UnhandledPromiseRejectionWarning: HttpError: Not Found
    at /home/runner/work/_actions/netlify/delta-action/v1/dist/index.js:2814:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.next (/home/runner/work/_actions/netlify/delta-action/v1/dist/index.js:4385:28)
    at async processPullRequest (/home/runner/work/_actions/netlify/delta-action/v1/dist/index.js:4974:28)
    at async run (/home/runner/work/_actions/netlify/delta-action/v1/dist/index.js:5013:3)
(node:2502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2502) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My configuration follows your examples:
```
      - name: Get size
        run: du -sk dist | cut -f1 > .delta.appSize && echo "kb (Total app size)" >> .delta.appSize

      - name: Run Delta
        uses: netlify/delta-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: master
```

It looks like the error is coming from the [octokit call to fetch comments](https://github.com/netlify/delta-action/blob/main/src/index.js#L33-L37). 
The action worked on the default branch, went through and added a commit comment on the current head commit of the default branch.
Any ideas?

-----

Love the idea for this action, thanks for sharing!
